// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjyfhvaorpfbifkfejff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqeWZodmFvcnBmYmlma2ZlamZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNTcyOTUsImV4cCI6MjA1NjczMzI5NX0.mHm37WJUkoPneblkfrw1MlNpbg3VIh6FoKC2C0f-oqI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);